### ISSUE TITLE
ASUS Tinker Board

### ISSUE THREAD

**Issue by imrehg** [balena-os/resin-os-device-support#42]
* **CPU**: Rockchip RK3288 Quad core 1.8GHz ARM Cortex-A17 CPU
* **GPU**: Mali T760
* **Memory**: 2GB Dual channel LPDDR3 memory
* **Storage**: micro-SD
* **Features**:
 * Gigabit LAN and Bluetooth 4.0 + EDR connectivity
 * 802.11 b/g/n Wi-Fi
 * 4x USB 2.0 ports
 * 40-pin Internal header with 28 GPIO pins
 * Contact points for PWM and S/PDIF signals
 * 1x 3.5mm Audio jack connection
 * CSI port for camera connection
 * DSI port supporting HD resolution
 * 1x HDMI 2.0 port to support 4K resolution

* **Link**: 
 * http://cpc.farnell.com/asus/90mb0qy1-m0eay0/tinker-board-2gb-1-8ghz-4k-gb/dp/SC14363
 * http://linuxgizmos.com/raspberry-pi-imitator-has-gbe-2gb-ram-and-4k-video/

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_11n7)

**Comment by xanview** [comment]
Anyone managed to get ResinOS running on the Asus Tinkerboard?

It's a really great board and makes a really great alternative for Raspberry Pi: significantly faster and double the ram, power management, audio input, etc. Having the same factor, it can also be used with the same enclosures as the Pi.

**Comment by xanview** [comment]
This seems relevant: https://github.com/sat8/yocto-tinkerboard

**Comment by shaunmulligan** [comment]
Hey @xanview ! yeah the Tinkerboard is a great little board. I was actually looking into how difficult it would be to support, it looks to be pretty straightforward. I think the preferred yocto BSP layer is this one: https://github.com/rockchip-linux/meta-rockchip which will most likely also support the [rock64](https://www.pine64.org/?page_id=7147) as well. 

I don't think anyone on the team currently has one of the Asus boards yet, but we will definitely be ordering a few :)

**Comment by hecontreraso** [comment]
I'm also very interested in make it resin + tinker board (:

**Comment by hecontreraso** [comment]
@xanview did you have any luck running resin OS on the board?

**Comment by anthify** [comment]
I would love to get this working with resin and running electron/chromium. Any advice on the necessary steps? I'm not very experienced with this kind of task, I largely work with frontend web technologies.

**Comment by imrehg** [comment]
Hi @anthify, yeah, device support is a bit more involved, but trying to make it easier by the day. Here's the documentation for adding custom board support https://resinos.io/docs/contrib/#support-for-additional-boards

**Comment by floion** [comment]
Device is supported for a while, closing issue

**Comment by imrehg** [comment]
@floion @shaunmulligan do we close these when the device type is supported? I thought we are just adding a flag for being supported, as it's easier to find. But closing makes sense, and might need to review the whole list again, if that's what we decide to do from this on?

**Comment by floion** [comment]
Yeah, I started closing them because it's way too many open and thought it was easier to close. But if we want to just add the label, we can do that too
