### ISSUE TITLE
Orange Pi Lite

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/resin-os-device-support#54]
Hardware specification

CPU
H3 Quad-core Cortex-A7 H.265/HEVC 4K

GPU
·Mali400MP2 GPU @600MHz
·Supports OpenGL ES 2.0

Memory (SDRAM)
512MB DDR3 (shared with GPU)

Onboard Storage
TF card (Max. 64GB) / MMC card slot

Features:

Realtek RTL8189ETV, IEEE 802.11 b/g/n
A CSI input connector Camera:
Supports 8-bit YUV422 CMOS sensor interface

Supports CCIR656 protocol for NTSC and PAL

Supports SM pixel camera sensor

Supports video capture solution up to 1080p@30fps

MIC
Supports HDMI output with HDCP
Supports HDMI CEC
Supports HDMI 30 function
Integrated CVBS
Supports simultaneous output of HDMI and CVBS

DC input can supply power, but USB OTG input don’t supply power
2 USB 2.0 HOST, one USB 2.0 OTG
Power Button(SW4), Recovery Button(SW3), Uboot Button(SW2)
Low-level peripherals 40 Pins Header,compatible with Raspberry Pi B+
GPIO(1x3) pin UART, ground.
Power led & Status led
IR input
Supported OS

Android, Ubuntu, Debian, Rasberry Pi Image

Link: http://www.orangepi.org/orangepilite/

**Comment by floion** [comment]
This is now supported for a while: https://github.com/balena-os/balena-allwinner/blob/master/orange-pi-lite.coffee
