### ISSUE TITLE
Fitlet2

### ISSUE THREAD

**Issue by imrehg** [balena-os/resin-os-device-support#63]
* **CPU**:  Intel Atom x7-E3950 | Intel Atom x5-E3930 | Intel Celeron J3455
* **GPU**: ? (integrated?)
* **Memory**: up to 16GB
* **Storage**: M.2 M-key 2260 | 2242 (SATA 3 6 Gbps) or eMMC
* **Features**:
  * mini DP 1.2 4K @ 60 Hz; HDMI 1.4 4K @ 30 Hz
  * LAN: Up to 4x Gbit Ethernet Intel i211
  * Wireless LAN: 802.11ac dual antenna + BT 4.2
  * USB: Up to 8 ports; 2x USB 3.0; Up to 6x USB 2.0
  * RS232 serial port
* **Link**: https://fit-iot.com/web/products/fitlet2/

**Comment by imrehg** [comment]
From the forums: https://forums.resin.io/t/will-you-be-supporting-the-intel-apollo-lake-atom/2276

**Comment by robeastham** [comment]
Any news on support for this device? Does the Resin team have to always explicitly provide support or could I try it out by following:

https://docs.resin.io/reference/resinOS/meta-resin/

**Comment by PeterSprague** [comment]
Any further update on support for this device?  For my work, this would be the most suitable device to deliver our product.  We need the higher processing power and ram provided.

Would an Intel NUC resin.io image work?

**Comment by DarianAnjuhal** [comment]
Same here. Any further informations? Did anyone try the Intel NUC?

**Comment by rwinscot** [comment]
We've had success using the Intel NUC with Resin OS 2.13.6+rev2 ... this profile works well with the Intel Atom x5-E3930. However, when moving to Balena OS 2.26.0+rev1, we get a "Default Boot Device Missing or Boot Failed" error.

**Comment by imrehg** [comment]
@rwinscot is it a newly provisioned system, or after doing a host OS update from 2.13.6?

**Comment by KingRial** [comment]
I am using NUC Balena OS 2.29.0+rev1 withthe fitlet2 and I see no problems poiting to "Balena Cloud" my custom "Open Balena".

Still need to complete my testing but I wanted to share my first results.

**Comment by floion** [comment]
This device is supported by the Intel NUC image. Closing issue

**Comment by jgentes** [comment]
@KingRial which fitlet2 model are you using? The Atom or Celeron version?

**Comment by KingRial** [comment]
> @KingRial which fitlet2 model are you using? The Atom or Celeron version?

Atom version

**Comment by jgentes** [comment]
I can confirm the NUC image works for us on the Atom version as well, we're also going to test the Celeron.

**Comment by PeterSprague** [comment]
I have used an older NUC image with the Celeron CPU.  Seemed to work fine.  Project is dormant, but can report more once I reactivate.
