### ISSUE TITLE
Will resin.io support ARMv5te device like pogoplug?

### ISSUE THREAD

**Issue by yahgoo** [balena-os/resin-os-device-support#65]
* **CPU**:  
ARMv5te Marvell Kirkwood 1.2GHz
* **GPU**: 
NA
* **Memory**:
256MB
* **Storage**:
128MB NAND
* **Features**:
  4 USB ports
  *
  *

* **Link**:
https://archlinuxarm.org/platforms/armv5/pogoplug-v2-pinkgray

**Comment by floion** [comment]
Hi, closing this item since we cannot have balenaOS running on this hardware which such limited storage
