### ISSUE TITLE
Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by rodcul** [balena-os/resin-os-device-support#67]

**Comment by matthewnessworthy** [comment]
Device support appears be be included in release https://github.com/resin-os/resin-raspberrypi/releases/tag/v2.12.5%2Brev1 as seen in the following version comparison https://github.com/resin-os/resin-raspberrypi/compare/v2.12.3+rev1...v2.12.5+rev1

**Comment by floion** [comment]
Closing this issue as device is supported for a while now
