### ISSUE TITLE
Orange Pi One

### ISSUE THREAD

**Issue by mrfu2** [balena-os/resin-os-device-support#68]
* **CPU**: [Allwinner H3](https://github.com/resin-os/resin-allwinner) ARM® Cortex™-A7 Quad-core @ 1200MHz
* **GPU**: Mali400MP2 @ 600MHz
* **Memory**: 512MB DDR3 SDRAM
* **Storage**: MicroSD (TF) card slot (Max 64GB)
* **Features**:
  * 10/100M Ethernet RJ45
  * A CSI camera connector input
  * 1x host USB
  * 1x USB OTG
  * HDMI output with HDCP
  * Supports HDMI CEC
  * 40 Pins Header, compatible with Raspberry Pi B+
* **Link**:
[Manufacturer](http://www.orangepi.org/orangepione/)
[Wiki page](https://linux-sunxi.org/Orange_Pi_Lite)
[Armbian](https://www.armbian.com/orange-pi-one/)
[Yocto](https://github.com/BladeGroup/meta-sunxi)
* **Price**: $9.99 / €8,65 (+ shipping)
* **Availability**: eBay + [AliExpress](https://www.aliexpress.com/item/Orange-Pi-One-ubuntu-linux-and-android-mini-PC-Beyond-and-Compatible-with-Raspberry-Pi-2/32603308880.html)

This board has the same CPU as:
* Orange Pi PC
* Orange Pi Lite
* Orange Pi PC Plus
* Orange Pi Plus 2E
* Orange Pi Zero Plus2

**Comment by floion** [comment]
This has now been contributed and is supported: https://github.com/balena-os/balena-allwinner/blob/master/orange-pi-one.coffee
